### ISSUE TITLE
Not an issue but... which ones are the dependencies?

### ISSUE THREAD

**Issue by sofiadparamo** [jczstudios/discord-chrome-presence#1]
Hi, I installed it and when running npm the console showed me warns with a list of dependencies. I didn't pay attention to that so it's not working and I don't have any way to install the dependencies...

**Comment by jczstudios** [comment]
The dependencies will install automatically. Just use `npm uninstall discord-chrome-presence --save` then go through the reinstall process and make sure you install the dependencies. You can also just look at the package.json file for all of the dependencies.

**Comment by sofiadparamo** [comment]
What should I do? :c https://pastebin.com/X5CcvkvW

**Comment by jczstudios** [comment]
This is not a problem, those dependencies aren't required for operation. If it's not working, have you installed the chrome extension? This is required for the installation.

**Comment by jczstudios** [comment]
The chrome extension can be found in the "extension" directory of this git repository. Look up how to add a chrome extension as a developer.
