### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Unhandled "error" event. ([ object Object])

### ISSUE THREAD

**Issue by zfeikg** [jczstudios/discord-chrome-presence#4]
I'm getting this error every time I try to start the server (I have the extension fully installed, btw):

```
C:\Users\Martin\discord-chrome-presence>npm start

> discord-chrome-presence@1.0.0 start C:\Users\Martin\discord-chrome-presence
> node app.js

Discord-Chrome-Presence is ready!
(node:3716) UnhandledPromiseRejectionWarning: Error: Unhandled "error" event. ([
object Object])
    at RP.emit (events.js:186:19)
    at rpc.login.then.catch (C:\Users\Martin\discord-chrome-presence\node_module
s\discord-rich-presence\index.js:54:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:3716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:3716) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
```

**Comment by Roki100** [comment]
same here

**Comment by Snow4DV** [comment]
the same :( 
`C:\Users\logmi\Documents\discord-chrome-presence-master>npm start

> discord-chrome-presence@1.0.0 start C:\Users\logmi\Documents\discord-chrome-presence-master
> node app.js

Discord-Chrome-Presence is ready!
(node:11076) UnhandledPromiseRejectionWarning: Error: Unhandled "error" event. ([object Object])
    at RP.emit (events.js:186:19)
    at rpc.login.then.catch (C:\Users\logmi\Documents\discord-chrome-presence-master\node_modules\discord-rich-presence\index.js:54:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:11076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11076) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by ghost** [comment]
Ditto 😢 
The error comes from the discord-rich-presence module, so it could be a bug in there and/or something wrong with the app that it logs in with:
`const client = require('discord-rich-presence')('417686773074886666');`
So I tried making my own Google Chrome app and using its client ID instead (`484805938608603140`) but it still doesn't work :cry:
It looks like this must be an issue with the discord-rich-presence module because just evaluating that line itself causes an error.

**Comment by ghost** [comment]
I FOUND THE ISSUE!!
This package is explicitly specifying discord-rich-presence version 0.0.6, but it has been updated to 0.0.7. discord-rich-presence depends on the latest discord.js/RPC, so the old drp package isn't compatible with the newest d.js/RPC package.
